DROP SCHEMA IF EXISTS COMINFO;
CREATE SCHEMA COMINFO;
SET SCHEMA COMINFO;

CREATE TABLE CATEGORY (
  ID    INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(256) NOT NULL,
  REGEX VARCHAR(1000) NOT NULL,
  UNIQUE (REGEX)
);

--asdsd

CREATE TABLE DATAROW (
  ID            INT AUTO_INCREMENT PRIMARY KEY,
  BOOKING_DATE  DATE           NOT NULL,
  VALUE_DATE    DATE           NOT NULL,
  BOOKING_TEXT  VARCHAR(2000)  NOT NULL,
  BOOKING_VALUE DECIMAL(20, 2) NOT NULL,
  CAT_ID INT NULL,
  UNIQUE (BOOKING_DATE, VALUE_DATE, BOOKING_TEXT, BOOKING_VALUE),
  FOREIGN KEY (CAT_ID) REFERENCES CATEGORY (ID) ON DELETE SET NULL
);

