DROP SCHEMA IF EXISTS COMINFO;
CREATE SCHEMA COMINFO;
SET SCHEMA COMINFO;

CREATE TABLE DATAROW(
ID INT AUTO_INCREMENT PRIMARY KEY,
BOOKING_DATE DATE NOT NULL,
BOOKING_TEXT VARCHAR(2000) NOT NULL,
VALUE_DATE DATE NOT NULL,
BOOKING_VALUE DECIMAL(20,2) NOT NULL
);
